### ISSUE TITLE
Revisit the role `oaklib` will play in this repo

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1214]
maybe for dynamic enumerations? `cvkit` only emits a term's id for now, and we frequently want MIxS style `termLabel [termId]`

see 
-  [ ] #947 
-  [ ] #959 
-  [ ] #844

**Comment by turbomam** [comment]
I tried to run `runoak --help` in a recent main commit with

> oaklib 0.5.6                                                                                        
> semsimian 0.2.11  

I got the response below. FWIW, I can run `runoak` in a fresh environment. It contained

- oaklib 0.5.22                                                                              
- semsimian 0.2.1

Poetry couldn't resolve a setup that included those versions in my nmdc-schema environment.

> ```
> Error from oaklib 0.5.6/semsimian 0.2.11  
> Traceback (most recent call last):
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/bin/runoak", line 5, in <module>
>     from oaklib.cli import main
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/oaklib/__init__.py", line 9, in <module>
>     from oaklib.selector import get_adapter, get_implementation_from_shorthand  # noqa:F401
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/oaklib/selector.py", line 15, in <module>
>     from oaklib.implementations.funowl.funowl_implementation import FunOwlImplementation
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/oaklib/implementations/__init__.py", line 39, in <module>
>     from oaklib.implementations.semsimian.semsimian_implementation import (
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/oaklib/implementations/semsimian/semsimian_implementation.py", line 10, in <module>
>     from semsimian import get_intersection, jaccard_similarity, mrca_and_score
> ImportError: cannot import name 'get_intersection' from 'semsimian' (/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/semsimian/__init__.py)
> ```
