### ISSUE TITLE
update linkml to 1.6.2

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#1374]
see also 
- #1365 

```shell
poetry update linkml linkml-runtime
```

> Updating dependencies
> Resolving dependencies... (3.4s)
> 
> Package operations: 0 installs, 1 update, 0 removals
> 
>   • Updating linkml (1.6.1 -> 1.6.2)
> 
> Writing lock file

```shell
poetry show linkml-runtime | grep version
```

> version      : 1.6.2                                                                  

```shell
poetry show linkml | grep version
```

> version      : 1.6.2

**Comment by turbomam** [comment]
```shell
poetry run gen-project \
        --exclude excel \
        --exclude graphql \
        --exclude jsonld \
        --exclude markdown \
        --exclude proto \
        --exclude shacl \
        --exclude shex \
        --exclude sqlddl \
        --include jsonldcontext \
        --include jsonschema \
        --include owl \
        --include python \
        --include rdf \
        -d project src/schema/nmdc.yaml && mv project/*.py nmdc_schema
```

> ALL_SCHEMAS = ['src/schema/nmdc.yaml']
> INFO:root:Skipping graphql as not in inclusion list: ['jsonldcontext', 'jsonschema', 'owl', 'python', 'rdf']
> INFO:root:Generating: jsonldcontext
> INFO:root: SCHEMA: src/schema/nmdc.yaml
> INFO:root: PARENT=project/jsonld
> INFO:root: jsonldcontext ARGS: {'mergeimports': True}
> INFO:root:  WRITING TO: project/jsonld/nmdc.context.jsonld
> INFO:root:Skipping jsonld as not in inclusion list: ['jsonldcontext', 'jsonschema', 'owl', 'python', 'rdf']
> INFO:root:Generating: jsonschema
> INFO:root: SCHEMA: src/schema/nmdc.yaml
> INFO:root: PARENT=project/jsonschema
> INFO:root:Using SchemaView with im=None
> INFO:root: jsonschema ARGS: {'mergeimports': True}
> INFO:root:Importing workflow_execution_activity as workflow_execution_activity from source src/schema/nmdc.yaml; base_dir=src/schema
> INFO:root:Importing core as core from source src/schema/nmdc.yaml; base_dir=src/schema
> INFO:root:Importing prov as prov from source src/schema/nmdc.yaml; base_dir=src/schema
> INFO:root:Importing basic_slots as basic_slots from source src/schema/nmdc.yaml; base_dir=src/schema
> INFO:root:Importing external_identifiers as external_identifiers from source src/schema/nmdc.yaml; base_dir=src/schema
> INFO:root:Importing sample_prep as sample_prep from source src/schema/nmdc.yaml; base_dir=src/schema
> INFO:root:Importing portal/sample_id as portal/sample_id from source src/schema/nmdc.yaml; base_dir=src/schema
> INFO:root:Importing linkml:types as /home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/linkml_runtime/linkml_model/model/schema/types from source src/schema/nmdc.yaml; base_dir=None
> INFO:root:Importing portal/mixs_inspired as portal/mixs_inspired from source src/schema/nmdc.yaml; base_dir=src/schema
> INFO:root:Importing portal/jgi_metatranscriptomics as portal/jgi_metatranscriptomics from source src/schema/nmdc.yaml; base_dir=src/schema
> INFO:root:Importing portal/jgi_metagenomics as portal/jgi_metagenomics from source src/schema/nmdc.yaml; base_dir=src/schema
> INFO:root:Importing portal/emsl as portal/emsl from source src/schema/nmdc.yaml; base_dir=src/schema
> INFO:root:Importing mixs as mixs from source src/schema/nmdc.yaml; base_dir=src/schema
> INFO:root:Importing annotation as annotation from source src/schema/nmdc.yaml; base_dir=src/schema
> INFO:root:  WRITING TO: project/jsonschema/nmdc.schema.json
> INFO:root:Skipping markdown as not in inclusion list: ['jsonldcontext', 'jsonschema', 'owl', 'python', 'rdf']
> INFO:root:Generating: owl
> INFO:root: SCHEMA: src/schema/nmdc.yaml
> INFO:root: PARENT=project/owl
> INFO:root:Using SchemaView with im=None
> INFO:root: owl ARGS: {'mergeimports': True}
> INFO:root:Importing workflow_execution_activity as workflow_execution_activity from source src/schema/nmdc.yaml; base_dir=src/schema
> INFO:root:Importing core as core from source src/schema/nmdc.yaml; base_dir=src/schema
> INFO:root:Importing prov as prov from source src/schema/nmdc.yaml; base_dir=src/schema
> INFO:root:Importing basic_slots as basic_slots from source src/schema/nmdc.yaml; base_dir=src/schema
> INFO:root:Importing external_identifiers as external_identifiers from source src/schema/nmdc.yaml; base_dir=src/schema
> INFO:root:Importing sample_prep as sample_prep from source src/schema/nmdc.yaml; base_dir=src/schema
> INFO:root:Importing portal/sample_id as portal/sample_id from source src/schema/nmdc.yaml; base_dir=src/schema
> INFO:root:Importing linkml:types as /home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/linkml_runtime/linkml_model/model/schema/types from source src/schema/nmdc.yaml; base_dir=None
> INFO:root:Importing portal/mixs_inspired as portal/mixs_inspired from source src/schema/nmdc.yaml; base_dir=src/schema
> INFO:root:Importing portal/jgi_metatranscriptomics as portal/jgi_metatranscriptomics from source src/schema/nmdc.yaml; base_dir=src/schema
> INFO:root:Importing portal/jgi_metagenomics as portal/jgi_metagenomics from source src/schema/nmdc.yaml; base_dir=src/schema
> INFO:root:Importing portal/emsl as portal/emsl from source src/schema/nmdc.yaml; base_dir=src/schema
> INFO:root:Importing mixs as mixs from source src/schema/nmdc.yaml; base_dir=src/schema
> INFO:root:Importing annotation as annotation from source src/schema/nmdc.yaml; base_dir=src/schema
> INFO:root:Importing linkml:units as /home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/linkml_runtime/linkml_model/model/schema/units from source None; base_dir=None
> INFO:root:Importing linkml:mappings as /home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/linkml_runtime/linkml_model/model/schema/mappings from source None; base_dir=None
> INFO:root:Importing linkml:types as /home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/linkml_runtime/linkml_model/model/schema/types from source None; base_dir=None
> INFO:root:Importing linkml:annotations as /home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/linkml_runtime/linkml_model/model/schema/annotations from source None; base_dir=None
> INFO:root:Importing linkml:extensions as /home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/linkml_runtime/linkml_model/model/schema/extensions from source None; base_dir=None
> WARNING:root:from_schema not populated for element has_input
> WARNING:root:from_schema not populated for element has_output
> WARNING:root:from_schema not populated for element id
> WARNING:root:from_schema not populated for element has_input
> WARNING:root:from_schema not populated for element has_output
> WARNING:root:from_schema not populated for element id
> WARNING:root:from_schema not populated for element has_input
> WARNING:root:from_schema not populated for element has_output
> WARNING:root:from_schema not populated for element id
> WARNING:root:from_schema not populated for element id
> WARNING:root:from_schema not populated for element has_input
> WARNING:root:from_schema not populated for element has_output
> WARNING:root:from_schema not populated for element id
> WARNING:root:from_schema not populated for element description
> WARNING:root:from_schema not populated for element id
> WARNING:root:from_schema not populated for element name
> WARNING:root:from_schema not populated for element dna_cont_well
> WARNING:root:from_schema not populated for element dna_cont_type
> WARNING:root:from_schema not populated for element dna_cont_type
> WARNING:root:from_schema not populated for element dna_cont_well
> WARNING:root:from_schema not populated for element rna_cont_well
> WARNING:root:from_schema not populated for element rna_cont_type
> WARNING:root:from_schema not populated for element rna_cont_type
> WARNING:root:from_schema not populated for element rna_cont_well
> WARNING:root:from_schema not populated for element al_sat
> WARNING:root:from_schema not populated for element al_sat_meth
> WARNING:root:from_schema not populated for element alternative_identifiers
> WARNING:root:from_schema not populated for element annual_precpt
> WARNING:root:from_schema not populated for element climate_environment
> WARNING:root:from_schema not populated for element cur_vegetation
> WARNING:root:from_schema not populated for element cur_vegetation_meth
> WARNING:root:from_schema not populated for element elev
> WARNING:root:from_schema not populated for element env_broad_scale
> WARNING:root:from_schema not populated for element env_local_scale
> WARNING:root:from_schema not populated for element env_medium
> WARNING:root:from_schema not populated for element extreme_event
> WARNING:root:from_schema not populated for element fire
> WARNING:root:from_schema not populated for element flooding
> WARNING:root:from_schema not populated for element gaseous_environment
> WARNING:root:from_schema not populated for element gold_biosample_identifiers
> WARNING:root:from_schema not populated for element heavy_metals
> WARNING:root:from_schema not populated for element heavy_metals_meth
> WARNING:root:from_schema not populated for element id
> WARNING:root:from_schema not populated for element lat_lon
> WARNING:root:from_schema not populated for element oxy_stat_samp
> WARNING:root:Multiple owl types {rdflib.term.URIRef('http://www.w3.org/2002/07/owl#Thing'), rdflib.term.URIRef('http://www.w3.org/2000/01/rdf-schema#Literal')}
> WARNING:root:from_schema not populated for element part_of
> WARNING:root:from_schema not populated for element ph_meth
> WARNING:root:from_schema not populated for element salinity_meth
> WARNING:root:from_schema not populated for element season_precpt
> WARNING:root:from_schema not populated for element sieving
> WARNING:root:from_schema not populated for element slope_aspect
> WARNING:root:from_schema not populated for element slope_gradient
> WARNING:root:from_schema not populated for element source_mat_id
> WARNING:root:from_schema not populated for element tot_carb
> WARNING:root:from_schema not populated for element tot_nitro_cont_meth
> WARNING:root:from_schema not populated for element tot_nitro_content
> WARNING:root:from_schema not populated for element tot_org_c_meth
> WARNING:root:from_schema not populated for element tot_org_carb
> WARNING:root:from_schema not populated for element water_cont_soil_meth
> WARNING:root:from_schema not populated for element water_content
> WARNING:root:from_schema not populated for element watering_regm
> Traceback (most recent call last):
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/bin/gen-project", line 8, in <module>
>     sys.exit(cli())
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/linkml/generators/projectgen.py", line 243, in cli
>     gen.generate(yamlfile, project_config)
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/linkml/generators/projectgen.py", line 145, in generate
>     gen_dump = gen.serialize(**serialize_args)
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/linkml/generators/owlgen.py", line 199, in serialize
>     self.as_graph()
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/linkml/generators/owlgen.py", line 185, in as_graph
>     self.add_class(cls)
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/linkml/generators/owlgen.py", line 352, in add_class
>     pre_node = condition_to_bnode(rule.preconditions)
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/linkml/generators/owlgen.py", line 344, in condition_to_bnode
>     ixn_listnode = self.transform_class_expression(expr, quantifier_predicate=OWL.someValuesFrom)
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/linkml/generators/owlgen.py", line 428, in transform_class_expression
>     x = self.transform_class_slot_expression(cls, slot, slot)
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/linkml/generators/owlgen.py", line 494, in transform_class_slot_expression
>     self._union_of([self.transform_class_slot_expression(cls, x, main_slot) for x in slot.any_of])
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/linkml/generators/owlgen.py", line 871, in _union_of
>     return self._boolean_expression(exprs, OWL.unionOf, **kwargs)
>   File "/home/mark/.cache/pypoetry/virtualenvs/nmdc-schema-_1824IzR-py3.9/lib/python3.9/site-packages/linkml/generators/owlgen.py", line 894, in _boolean_expression
>     raise ValueError(f"None in exprs: {exprs}")
> ValueError: None in exprs: [None, None]
> make: *** [Makefile:102: gen-project] Error 1
>

**Comment by turbomam** [comment]
works when owl generation is excluded
