### ISSUE TITLE
Cannot find `get_nmdc_dict()` method definition

### ISSUE THREAD

**Issue by sujaypatil96** [microbiomedata/nmdc-schema#270]
When testing the `validate-nmdc-json` command line tool on the poetry [branch](https://github.com/microbiomedata/nmdc-schema/tree/spatil/poetrify-nmdc-schema), by running the following command:

```
poetry run validate-nmdc-schema --input ~/path/to/data.json --database-set set_name
```

I run into the following error:

```
➜  nmdc-schema git:(spatil/poetrify-nmdc-schema) ✗ poetry run validate-nmdc-json --input test/data/biosample_test.json --database-set biosample_set
RDFLib Version: 5.0.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/sujaypatil/Library/Caches/pypoetry/virtualenvs/nmdc-schema-w10_cBbN-py3.9/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sujaypatil/Library/Caches/pypoetry/virtualenvs/nmdc-schema-w10_cBbN-py3.9/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/sujaypatil/Library/Caches/pypoetry/virtualenvs/nmdc-schema-w10_cBbN-py3.9/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sujaypatil/Library/Caches/pypoetry/virtualenvs/nmdc-schema-w10_cBbN-py3.9/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/sujaypatil/Desktop/nmdc-schema/nmdc_schema/validate_nmdc_json.py", line 86, in cli
    if is_valid_json(input, database_set):
  File "/Users/sujaypatil/Desktop/nmdc-schema/nmdc_schema/validate_nmdc_json.py", line 64, in is_valid_json
    jsonschema.validate(instance=json_data, schema=get_nmdc_dict())
NameError: name 'get_nmdc_dict' is not defined
```

Meaning the `get_nmdc_dict()` method hasn't been defined anywhere.

**Comment by wdduncan** [comment]
The call should be made to [get_jsonschema_dict()](https://github.com/microbiomedata/nmdc-schema/blob/be944fba292d4763218541b9093a79ddacac41b9/util/nmdc_data.py#L92).  
Thanks for catching this! I will fix.
