### ISSUE TITLE
error during github-pages GH action

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#429]
Sorry, I probably added or removed something from `main`

The `gh-deploy` Makefile rule still seems to work

> INFO     -  Copying '/home/runner/work/nmdc-schema/nmdc-schema/mkdocs_html' to 'gh-pages' branch and pushing to GitHub.
To https://github.com/microbiomedata/nmdc-schema
 ! [rejected]        gh-pages -> gh-pages (fetch first)
error: failed to push some refs to 'https://github.com/microbiomedata/nmdc-schema'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Traceback (most recent call last):
  File "/home/runner/work/nmdc-schema/nmdc-schema/.venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/runner/work/nmdc-schema/nmdc-schema/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/runner/work/nmdc-schema/nmdc-schema/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/runner/work/nmdc-schema/nmdc-schema/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/runner/work/nmdc-schema/nmdc-schema/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/work/nmdc-schema/nmdc-schema/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/work/nmdc-schema/nmdc-schema/.venv/lib/python3.9/site-packages/mkdocs/__main__.py", line 216, in gh_deploy_command
    gh_deploy.gh_deploy(
  File "/home/runner/work/nmdc-schema/nmdc-schema/.venv/lib/python3.9/site-packages/mkdocs/commands/gh_deploy.py", line 108, in gh_deploy
    ghp_import.ghp_import(
  File "/home/runner/work/nmdc-schema/nmdc-schema/.venv/lib/python3.9/site-packages/ghp_import.py", line 285, in ghp_import
    git.check_call('push', opts['remote'], opts['branch'])
  File "/home/runner/work/nmdc-schema/nmdc-schema/.venv/lib/python3.9/site-packages/ghp_import.py", line 119, in check_call
    sp.check_call(['git'] + list(args), **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'push', 'origin', 'gh-pages']' returned non-zero exit status 1.
make: *** [Makefile:164: gh-deploy] Error 1
Error: Process completed with exit code 2.

**Comment by turbomam** [comment]
when desperate, try 
- deleting the gh-pages branch
- running the "pages-build-deployment" action
- ensuring that the gh-pages branch is still set as the source for GH pages https://github.com/microbiomedata/nmdc-schema/settings/pages
