### ISSUE TITLE
gen-doc build process not going through because of missing dependency

### ISSUE THREAD

**Issue by sujaypatil96** [microbiomedata/nmdc-schema#492]
```
poetry run gen-doc src/schema/nmdc.yaml --template-directory src/doc-templates -d docs
Traceback (most recent call last):
  File "/Users/sujaypatil/Desktop/nmdc-schema/.venv/bin/gen-doc", line 5, in <module>
    from linkml.generators.docgen import cli
  File "/Users/sujaypatil/Desktop/nmdc-schema/.venv/lib/python3.8/site-packages/linkml/generators/docgen.py", line 11, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by sujaypatil96** [comment]
* Find all your virtual environments associated with the repo
  * `poetry env list --full-path`
* Remove all virtual environments
  * `poetry env remove name-of-virtual-environment`
Note: `name-of-virtual-environment` would be everything after the last forward slash in the full path
* Remove poetry.lock file
* Regenerate poetry.lock file based on pyproject.toml file
* `poetry install`
