### ISSUE TITLE
problems with automated generation and deployment of schema docs

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-schema#721]
- [x] static pages not getting included
- [ ] make deploy complains about un-clean git index

**Comment by turbomam** [comment]
maybe resolving the second sub-issue will address the first too

@turbomam added artifact generation steps to `make site` and that leads to uncommitted files

We have observed that clicking many links in a local testdocs can lead to the page becoming frozen

**Comment by turbomam** [comment]
`make deploy` includes the static content but the documentation deploy action deosn't

**Comment by turbomam** [comment]
`make deploy`

```
INFO     -  Copying '/Users/MAM/Documents/gitrepos/nmdc-schema/site' to 'gh-pages' branch and pushing to GitHub.
To github.com:microbiomedata/nmdc-schema.git
 ! [rejected]          gh-pages -> gh-pages (fetch first)
error: failed to push some refs to 'github.com:microbiomedata/nmdc-schema.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Traceback (most recent call last):
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/nmdc-schema-MTtWF7zd-py3.10/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/nmdc-schema-MTtWF7zd-py3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/nmdc-schema-MTtWF7zd-py3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/nmdc-schema-MTtWF7zd-py3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/nmdc-schema-MTtWF7zd-py3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/nmdc-schema-MTtWF7zd-py3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/nmdc-schema-MTtWF7zd-py3.10/lib/python3.10/site-packages/mkdocs/__main__.py", line 280, in gh_deploy_command
    gh_deploy.gh_deploy(
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/nmdc-schema-MTtWF7zd-py3.10/lib/python3.10/site-packages/mkdocs/commands/gh_deploy.py", line 127, in gh_deploy
    ghp_import.ghp_import(
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/nmdc-schema-MTtWF7zd-py3.10/lib/python3.10/site-packages/ghp_import.py", line 285, in ghp_import
    git.check_call('push', opts['remote'], opts['branch'])
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/nmdc-schema-MTtWF7zd-py3.10/lib/python3.10/site-packages/ghp_import.py", line 119, in check_call
    sp.check_call(['git'] + list(args), **kwargs)
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'push', 'origin', 'gh-pages']' returned non-zero exit status 1.
make: *** [mkd-gh-deploy] Error 1
```

**Comment by turbomam** [comment]
manual execution of `make deploy` (and understanding the un-clean git index complaint are less important now that merging a PR triggers a GH action that includes the static MD pages
